.build_script_template : &build_script_definition
  script:
    - mkdir -p ~/ros_ws/src
    - cd ~/ros_ws
    - catkin_make -DCMAKE_BUILD_TYPE=Release
    - cd src
    - cp -r /builds/$GITLAB_USER_LOGIN/ontologenius .
    - cd ..
    - catkin_make -DCMAKE_BUILD_TYPE=Release

.test_script_template : &test_script_definition_py3
  script:
    - mkdir -p ~/ros_ws/src
    - cd ~/ros_ws
    - catkin_make -DCMAKE_BUILD_TYPE=Release
    - cd src
    - cp -r /builds/$GITLAB_USER_LOGIN/ontologenius .
    - cd ..
    - pip3 install requests --user
    - source devel/setup.bash
    - catkin_make -DCMAKE_BUILD_TYPE=Release
    - source devel/setup.bash
    - catkin_make run_tests_ontologenius_rostest -j1 -DCMAKE_BUILD_TYPE=Release && catkin_make test -j1 -DCMAKE_BUILD_TYPE=Release

.noetic_before_template : &noetic_before_definition
  before_script:
  - source /opt/ros/noetic/setup.bash
  - apt-get update -qq && apt-get install -y libcppunit-1.15-0 libcppunit-dev libtinyxml-dev git-all python3-rosdep python3-pip libcurl4-openssl-dev

stages:
  - build
  - test

run-test-noetic:
  stage: test
  image: ros:noetic-perception-focal
  <<: *noetic_before_definition
  <<: *test_script_definition_py3

run-build-noetic:
  image: ros:noetic-perception-focal
  stage: build
  <<: *noetic_before_definition
  <<: *build_script_definition
