flow:
  - ontologenius::ReasonerChain
  - ontologenius::ReasonerDictionary
  - ontologenius::ReasonerGeneralize
  - ontologenius::ReasonerInverseOf
  - ontologenius::ReasonerRangeDomain
  - ontologenius::ReasonerSymmetric
  - ontologenius::ReasonerAnonymous
  - ontologenius::ReasonerTransitivity
ontologenius::ReasonerGeneralize:
  min_count : 2
  min_percent : 0.6